# Generated by Django 4.1.12 on 2023-11-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_imgage',
            new_name='product_image',
        ),
    ]
