# Generated by Django 4.1.12 on 2024-03-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_product_imgage_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
