# Generated by Django 4.1.12 on 2024-03-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orderplaced_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='payment_id',
            new_name='transaction_id',
        ),
    ]
